
spring.profiles.active: test

spring:
  datasource:
    url: jdbc:h2:mem:simple-kata-rpg-test-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true