logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:simple-kata-rpg-test-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
    platform: h2
    data: classpath:data_test.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hiberate:
      ddl-auto: create
  h2:
    console:
      enabled: true


